
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Sue-Ting Yeh
tagline: Postgraduate Student
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: rockkrisklose@gmail.com
phone: +44 745 270 3841
#website: blog.webjeda.com #do not add http://
linkedin: suetingyeh
github: sueting
#twitter: '@webjeda'


# Tracker
#analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
